# Generated by Django 4.0.5 on 2023-12-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
